version: '3.8'

services:
  backend:
    build: ./backend
    container_name: my_backend
    ports:
      - "8000:5000"
    restart: always  # <-- Phase 10: High Availability
    environment:
      - OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}
      # - MONGODB_URI=your_database_url_here (Add your environment variables here later)
    volumes:
      - ./medibook.db:/app/medibook.db  # This is the "Magic Line"
      - ./chroma_data:/app/chroma_data  # Save your AI training data too

  frontend:
    build: ./frontend
    container_name: my_frontend
    ports:
      - "3000:5173"
    restart: always  # <-- Phase 10: High Availability
    depends_on:
      - backend      # Ensures backend starts before frontend
    environment:
      - OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}
